name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # Replace this with your build folder if using React/Next etc.

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
